### ISSUE TITLE
Readin' from a non existant file, audio mixing error.

### ISSUE THREAD

**Issue by epicgamerXDLOL** [SaltiestOrange4/Python-games#1]
with open("Meals.txt",'r')as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Meals.txt'

pygame.mixer.music.load(file)
pygame.error: Couldn't open 'The Hanging Tree - MUSIC VIDEO - [The Hunger Games Mockingjay Pt.1 Score (James Newton Howard)].mp3'

**Comment by longwatermelon** [comment]
That is rather unfortunate, I hope SaltiestOrange4 tested his code before posting it on github.

**Comment by interesting84** [comment]
Displaying code as finished before tested is very unprofessional But I am glad that we can all work together to improve each other through the github communityh

**Comment by SaltiestOrange4** [comment]
Hello. Thank you for bringing up these issues. I took out the audio as there was no use for it in the game. Also, I am not sure about the problem about reading from a nonexistent file. It works for me. Try changing the path of these files according to your own system.

**Comment by SaltiestOrange4** [comment]
@epicgamerXDLOL check my previous post, and if there are any problems, pls post it in here. Otherwise, I will be closing this issue tomorrow.
