### ISSUE TITLE
I believe you have a very inefficient algorithm in your tic tac toe game.

### ISSUE THREAD

**Issue by longwatermelon** [SaltiestOrange4/Python-games#2]
![image](https://user-images.githubusercontent.com/73869536/123556146-68bb9480-d73e-11eb-8fdc-f5c9622d93e1.png)

I hope you consider my very elegantly cleverly engineered solution.

**Comment by epicgamerXDLOL** [comment]
Lol, Is that vim, on Linux?. But anyways You should Create a Pull Request.

**Comment by interesting84** [comment]
agreed

**Comment by longwatermelon** [comment]
Sorry, but I am not as tech savvy as the average child these days. Will one of you youngsters make a pull request for me?

**Comment by longwatermelon** [comment]
> Lol, Is that vim, on Linux?. But anyways You should Create a Pull Request.

Indeed, that is vim on Linux, specifically Linux Mint. I am truly a tech wiz and I know quite a lot about computers.

**Comment by interesting84** [comment]
ah a linux kid interesting

**Comment by longwatermelon** [comment]
I would appreciate it if you could create a pull request for me, adolescent child.

**Comment by interesting84** [comment]
Ok Mr Linux

**Comment by interesting84** [comment]
actually i am very sorry
Currently I am unable to make a pull request

**Comment by longwatermelon** [comment]
It is fine young one. I am sure epicgamerXDLOL is capable of creating a pull request.

**Comment by interesting84** [comment]
'I am srooy my elderly finger bones wear out quickly

**Comment by longwatermelon** [comment]
I understand. Although aspiration arthritis is not easy to go through, we all must experience it as we grow older.

**Comment by SaltiestOrange4** [comment]
> ![image](https://user-images.githubusercontent.com/73869536/123556146-68bb9480-d73e-11eb-8fdc-f5c9622d93e1.png)
> 
> I hope you consider my very elegantly cleverly engineered solution.

Hey. Thank you for the other option. It certainly does work and is more efficient. Ill change it as soon as possible.
